name: golang-ci
on:
  pull_request:
    paths:
      - "**.go"
      - .github/workflows/golangci.yml
jobs:
  golangci-link:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: golangci-list
        uses: reviewdog/action-golangci-lint@v2 
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          golangci_list_flags: "--config=./.golangci.yml ./..."
          fail_on_error: true
          reporter: "github-pr-review"
